/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutPendenteRouteImport } from './routes/checkout.pendente'
import { Route as CheckoutErroRouteImport } from './routes/checkout.erro'
import { Route as ApiMercadoPagoWebhookRouteImport } from './routes/api/mercado-pago-webhook'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPendenteRoute = CheckoutPendenteRouteImport.update({
  id: '/checkout/pendente',
  path: '/checkout/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutErroRoute = CheckoutErroRouteImport.update({
  id: '/checkout/erro',
  path: '/checkout/erro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMercadoPagoWebhookRoute = ApiMercadoPagoWebhookRouteImport.update({
  id: '/api/mercado-pago-webhook',
  path: '/api/mercado-pago-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/api/mercado-pago-webhook': typeof ApiMercadoPagoWebhookRoute
  '/checkout/erro': typeof CheckoutErroRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/api/mercado-pago-webhook': typeof ApiMercadoPagoWebhookRoute
  '/checkout/erro': typeof CheckoutErroRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/api/mercado-pago-webhook': typeof ApiMercadoPagoWebhookRoute
  '/checkout/erro': typeof CheckoutErroRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/reset-password'
    | '/checkout'
    | '/api/mercado-pago-webhook'
    | '/checkout/erro'
    | '/checkout/pendente'
    | '/checkout/sucesso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/reset-password'
    | '/checkout'
    | '/api/mercado-pago-webhook'
    | '/checkout/erro'
    | '/checkout/pendente'
    | '/checkout/sucesso'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/reset-password'
    | '/_authenticated/checkout'
    | '/api/mercado-pago-webhook'
    | '/checkout/erro'
    | '/checkout/pendente'
    | '/checkout/sucesso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiMercadoPagoWebhookRoute: typeof ApiMercadoPagoWebhookRoute
  CheckoutErroRoute: typeof CheckoutErroRoute
  CheckoutPendenteRoute: typeof CheckoutPendenteRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pendente': {
      id: '/checkout/pendente'
      path: '/checkout/pendente'
      fullPath: '/checkout/pendente'
      preLoaderRoute: typeof CheckoutPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/erro': {
      id: '/checkout/erro'
      path: '/checkout/erro'
      fullPath: '/checkout/erro'
      preLoaderRoute: typeof CheckoutErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mercado-pago-webhook': {
      id: '/api/mercado-pago-webhook'
      path: '/api/mercado-pago-webhook'
      fullPath: '/api/mercado-pago-webhook'
      preLoaderRoute: typeof ApiMercadoPagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiMercadoPagoWebhookRoute: ApiMercadoPagoWebhookRoute,
  CheckoutErroRoute: CheckoutErroRoute,
  CheckoutPendenteRoute: CheckoutPendenteRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
